name: "Release"

on:
  push:
    branches: [ "main" ]

  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if release
        id: release-check
        shell: bash
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          EVENT_NAME: ${{ github.event_name }}
        run: |
          isrelease="false"
          if [[ $EVENT_NAME == "push" && $COMMIT_MESSAGE == "release: "* ]]; then
            isrelease="true"
          elif [[ $EVENT_NAME == "workflow_dispatch" ]]; then
            isrelease="true"
          fi
          echo "is-release=$isrelease" >> "$GITHUB_OUTPUT"

      - name: Print result
        shell: bash
        run: |
          echo ${{ steps.release-check.outputs.is-release }}
